language: julia
os:
    - osx
    - linux
julia:
    - 0.5
    - 0.6
    - nightly
notifications:
    email: false
sudo: false
addons:
    apt:
        packages:
            - gfortran
before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install gcc; fi
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Dopri"); Pkg.test("Dopri"; coverage=true)';
after_success:
- julia -e 'cd(Pkg.dir("Dopri")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
